apiVersion: v1
name: kafka
description: A minimal Kafka deployment using Bitnami
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    version: ~31.4.0
    repository: oci://registry-1.docker.io/bitnamicharts